In [ ]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from scipy import linalg, optimize

In [4]:
np.info(optimize.fmin)

 fmin(func, x0, args=(), xtol=0.0001, ftol=0.0001, maxiter=None, maxfun=None,
      full_output=0, disp=1, retall=0, callback=None)

Minimize a function using the downhill simplex algorithm.

This algorithm only uses function values, not derivatives or second
derivatives.

Parameters
----------
func : callable func(x,*args)
    The objective function to be minimized.
x0 : ndarray
    Initial guess.
args : tuple, optional
    Extra arguments passed to func, i.e. ``f(x,*args)``.
callback : callable, optional
    Called after each iteration, as callback(xk), where xk is the
    current parameter vector.
xtol : float, optional
    Relative error in xopt acceptable for convergence.
ftol : number, optional
    Relative error in func(xopt) acceptable for convergence.
maxiter : int, optional
    Maximum number of iterations to perform.
maxfun : number, optional
    Maximum number of function evaluations to make.
full_output : bool, optional
    Set to True if fopt and warnflag outputs are desi

In [7]:
#slicing
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
y=x[1:7:2]
z = x[0:9:3]
print y,z

[1 3 5] [0 3 6]


In [10]:
x[-2:]

array([8, 9])

In [11]:
x[-3:3:-1]

array([7, 6, 5, 4])

In [12]:
# indexing for array with tuple
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])

In [13]:
x.shape

(2, 3, 1)

In [18]:
print x[0,0,0]

1


In [19]:
print x[0,1]

[2]


In [28]:
x[1]

array([[4],
       [5],
       [6]])

In [29]:
x.ndim

3

In [32]:
obj = (slice(1,10,5), slice(None,None,-1)); x[obj]

array([[[6],
        [5],
        [4]]])

In [33]:
x = np.array([[1, 2], [3, 4], [5, 6]])
#rows are [0,1,2], columns are [0,1,0]
x[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

In [36]:
x = np.array([[ 0,  1,  2],
           [ 3,  4,  5],
           [ 6,  7,  8],
           [ 9, 10, 11]])
rows = np.array([0, 3], dtype=np.intp)
columns = np.array([0, 2], dtype=np.intp)
rows[:, np.newaxis]
columns[:,np.newaxis]

array([[0],
       [2]])

In [37]:
x[rows[:, np.newaxis], columns]

array([[ 0,  2],
       [ 9, 11]])

In [38]:
x[np.ix_(rows, columns)]

array([[ 0,  2],
       [ 9, 11]])

In [39]:
x[1:2, 1:3]

array([[4, 5]])

In [40]:
x[1:2, [1, 2]]

array([[4, 5]])

In [41]:
# field access
x = np.zeros((2,2), dtype=[('a', np.int32), ('b', np.float64, (3,3))])
x['a'].shape

(2, 2)

In [43]:
#If the accessed field is a sub-array, the dimensions of the sub-array are appended to the shape of the result.
x['b'].shape

(2, 2, 3, 3)

In [44]:
x['b'].dtype

dtype('float64')

In [53]:
x.flat[0]

(0, [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]])